// ===============================
// Kiiiiiiir AI - Code Generator
// ===============================

const promptInput = document.getElementById("prompt");
const codeType = document.getElementById("codeType");
const codeResult = document.querySelector("#codeResult code");
const preview = document.getElementById("preview");


// ساخت کد
function generateCode() {

    const prompt = promptInput.value.trim();
    const type = codeType.value;

    if (!prompt) {
        showMessage("⚠️ اول توضیح بده چی می‌خوای بسازیم!");
        promptInput.focus();
        return;
    }

    let code = "";

    if (type === "html") {

        code = `<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>پروژه من</title>

    <style>
        body {
            font-family: Arial, sans-serif;
            background: #10101d;
            color: white;
            text-align: center;
            padding: 50px;
        }

        .box {
            max-width: 600px;
            margin: auto;
            padding: 30px;
            border-radius: 20px;
            background: #1b1b2b;
            box-shadow: 0 0 30px rgba(124,92,255,.3);
        }

        button {
            padding: 12px 20px;
            border: none;
            border-radius: 10px;
            background: #7c5cff;
            color: white;
            cursor: pointer;
        }
    </style>
</head>

<body>

    <div class="box">

        <h1>🚀 پروژه ساخته شد!</h1>

        <p>${escapeHTML(prompt)}</p>

        <button onclick="alert('سلام از پروژه جدید!')">
            کلیک کن
        </button>

    </div>

</body>
</html>`;

    }

    else if (type === "css") {

        code = `/* CSS Generated by Kiiiiiiir AI */

body {
    margin: 0;
    padding: 0;
    background: #10101d;
    color: white;
    font-family: Arial, sans-serif;
}

.container {
    max-width: 1000px;
    margin: auto;
    padding: 30px;
}

.button {
    padding: 15px 25px;
    border-radius: 12px;
    border: none;
    background: linear-gradient(135deg, #7c5cff, #00e5ff);
    color: white;
    cursor: pointer;
}

/* درخواست کاربر:
${prompt}
*/`;

    }

    else if (type === "javascript") {

        code = `// JavaScript Generated by Kiiiiiiir AI

document.addEventListener("DOMContentLoaded", () => {

    console.log("🤖 Kiiiiiiir AI اجرا شد!");

    // درخواست کاربر:
    // ${prompt}

    const button = document.querySelector("button");

    if (button) {

        button.addEventListener("click", () => {

            alert("🚀 کد JavaScript شما اجرا شد!");

        });

    }

});`;

    }


    // نمایش کد
    codeResult.textContent = code;

    // اگر HTML بود، پیش‌نمایش بده
    if (type === "html") {
        preview.srcdoc = code;
    } else {
        preview.srcdoc = `
            <html>
            <body style="
                font-family:Arial;
                padding:30px;
                background:#10101d;
                color:white;
                text-align:center;
            ">
                <h2>💻 ${type.toUpperCase()}</h2>
                <p>کد با موفقیت ساخته شد.</p>
                <p>برای اجرای این نوع کد، آن را داخل پروژه خود قرار بده.</p>
            </body>
            </html>
        `;
    }

    showMessage("✅ کد با موفقیت ساخته شد!");

    document.querySelector(".result-box").scrollIntoView({
        behavior: "smooth"
    });
}


// کپی کردن کد
function copyCode() {

    const code = codeResult.textContent;

    if (!code || code.includes("کدی که ساخته می‌شود")) {
        showMessage("⚠️ هنوز کدی ساخته نشده!");
        return;
    }

    navigator.clipboard.writeText(code)
        .then(() => {
            showMessage("📋 کد کپی شد!");
        })
        .catch(() => {
            showMessage("❌ کپی کردن انجام نشد.");
        });
}


// نمایش پیام
function showMessage(message) {

    let box = document.querySelector(".ai-message");

    if (!box) {

        box = document.createElement("div");

        box.className = "ai-message";

        box.style.position = "fixed";
        box.style.bottom = "25px";
        box.style.left = "50%";
        box.style.transform = "translateX(-50%)";
        box.style.padding = "14px 22px";
        box.style.background = "#171727";
        box.style.color = "white";
        box.style.border = "1px solid #7c5cff";
        box.style.borderRadius = "14px";
        box.style.zIndex = "99999";
        box.style.boxShadow = "0 10px 40px rgba(0,0,0,.4)";
        box.style.transition = "0.3s";

        document.body.appendChild(box);
    }

    box.textContent = message;
    box.style.opacity = "1";

    clearTimeout(box.timer);

    box.timer = setTimeout(() => {
        box.style.opacity = "0";
    }, 2500);
}


// جلوگیری از وارد شدن HTML خطرناک به متن
function escapeHTML(text) {

    return text
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");

}


// اجرای اولیه
console.log("🤖 Kiiiiiiir AI آماده است!");